app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='order')),
]


if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from orders.views import create_order

app_name = 'orders'

urlpatterns = [
   path('create-order/', create_order, name='add_order'),
]

orders/models.py
from django.db import models

from goods.models import Product
from users.models import User

# Create your models here.


class OrderItemQuerySet(models.QuerySet):
    def total_price(self):
        return sum(cart.order_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, default=None, verbose_name='Пользователь')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    requires_delivery = models.BooleanField(default=False, verbose_name='Требуется доставка')
    address_delivery = models.TextField(null=True, blank=True, verbose_name='Адрес доставки')
    payment_on_get = models.BooleanField(default=False, verbose_name='Оплата при получении')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=50, default='В обработке', verbose_name='Статус заказа')

    class Meta:
        db_table = 'order'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name}'


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(to=Product, on_delete=models.SET_DEFAULT, null=True, default=None, verbose_name='Продукт')
    name = models.CharField(max_length=150, verbose_name='Название')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')

    class Meta:
        db_table = 'order_item'
        verbose_name = 'Проданный товар'
        verbose_name_plural = 'Проданный товары'


    objects = OrderItemQuerySet.as_manager()


    def order_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f'Товар {self.name} | Заказ № {self.order.pk}'

orders/forms.py
from django import forms


class CreateOrderForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(choices=[('0', 'False'), ('1', 'True'),])
    address_delivery = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(choices=[('0', 'False'), ('1', 'True'),])

orders/views.py
from django.db import transaction
from django.shortcuts import render, redirect
from django.contrib import messages
from carts.models import Cart
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem
from django.forms import ValidationError


# Create your views here.
def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    cart_items = Cart.objects.filter(user=request.user)
                    if cart_items.exists():
                        # Создать заказ
                        order = Order.objects.create(
                            user=request.user,
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            address_delivery=form.cleaned_data['address_delivery'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )

                        for cart_item in cart_items:
                            product = cart_item.cart_product
                            name = cart_item.cart_product.name
                            price = cart_item.cart_product.sell_price()
                            quantity = cart_item.cart_quantity

                            if product.quantity < quantity:
                                raise ValidationError(
                                    f'Недостаточно количество товара {name} на складе | В наличии {product.quantity}')

                            OrderItem.objects.create(
                                order=order,
                                name=name,
                                price=price,
                                quantity=quantity
                            )
                            product.quantity - quantity
                            product.save()
                        cart_items.delete()
                        messages.success(request, 'Заказ оформлен')
                        return redirect('user:profile')
            except ValidationError as e:
                messages.warning(request, str(e))
                return redirect('user:profile')
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
        }
        form = CreateOrderForm(initial=initial)

    context = {
        'form': form
    }
    return render(request, "orders/create_order.html", context)

orders/templates/orders/create_order.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
   <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <div class="container">
                            <h3 class="text-center mb-4">Выбранные товары</h3>
                            <div class="container" id="cart-items-container">
                                <!-- Разметка корзины -->
                               {% include 'carts/cart.html' %}
                                <!-- Закончилась разметка корзины -->
                            </div>
                        </div>
                        <!-- Детали заказа -->
                        <div class="container">
                            <h3 class="text-center">Детали заказа</h3>
                            <div class="card mb-3">
                                <div class="card-body">
                                    <form action="{% url 'order:add_order' %}" method="POST">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-md-6 mb-3">
                                                <label for="id_first_name" class="form-label">Имя*:</label>
                                                <input type="text" class="form-control" id="id_first_name"
                                                    name="first_name" required>
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_last_name" class="form-label">Фамилия*:</label>
                                                <input type="text" class="form-control" id="id_last_name" name="last_name" required>
                                            </div>
                                            <div class="col-md-6 mb-3">
                                                <label for="id_phone_number" class="form-label">Номер телефона*:</label>
                                                <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                                    placeholder="В формате: XXX-XXX-XX-XX"
                                                    required>
                                            </div>
                                            <div class="col-md-12 mb-3">
                                                <label for="delivery" class="form-label">Способ доставки: </label>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                                        id="id_requires_delivery" value="1" checked>
                                                    <label class="form-check-label" for="id_requires_delivery">Нужна
                                                        доставка</label>
                                                </div>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                                        id="id_requires_delivery" value="0">
                                                    <label class="form-check-label" for="id_requires_delivery">Самовывоз</label>
                                                </div>
                                            </div>
                                            <div class="mb-3" id="deliveryAddressField">
                                                <label class="form-label">Адрес
                                                    доставки*:</label>
                                                <textarea class="form-control"
                                                    name="address_delivery" rows="2"></textarea>
                                            </div>
                                            <div class="col-md-12 mb-3">
                                                <label class="form-label">Способ оплаты: </label>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                                        id="id_payment_on_get" value="0" checked>
                                                    <label class="form-check-label" for="id_payment_on_get">Оплата
                                                        картой</label>
                                                </div>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                                        id="id_payment_on_get" value="1">
                                                    <label class="form-check-label" for="id_payment_on_get">Наличными/картой
                                                        при плучении</label>
                                                </div>
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-dark">Оформить заказ</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}