app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='order')),
]


if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import *

app_name = 'users'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('register/', user_register, name='register'),
    path('profile/', user_profile, name='profile'),
    path('user-cart/', user_cart, name='user-cart'),
    path('logout/', user_logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'autofocus': True,
        'class': 'form-control',
        'placeholder': 'Введите ваше имя пользователя',
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'autofocus': True,
        'class': 'form-control',
        'placeholder': 'Введите ваш пароль',
    }))

    class Meta:
        model = User


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class UserChangesForm(UserChangeForm):
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'form-control mt-3',
    }), required=False)

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'readonly': True
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'readonly': True,
    }))

    class Meta:
        model = User
        fields = ('image', 'first_name', 'last_name', 'username', 'email')

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from carts.models import Cart
from users.forms import UserLoginForm, UserRegistrationForm, UserChangesForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse


# Create your views here.


def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('main:home'))
    else:
        form = UserLoginForm()

    context = {
        'form': form,
    }
    return render(request, "users/login.html", context)


def user_register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            login(request, user)
            if request.POST.get('next', None):
                return HttpResponseRedirect(request.POST.get('next'))

            return HttpResponseRedirect(reverse('main:home'))
    else:
        form = UserRegistrationForm()
    context = {
        'form': form,
    }
    return render(request, "users/registration.html", context)


@login_required
def user_profile(request):
    if request.method == 'POST':
        form = UserChangesForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = UserChangesForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, "users/profile.html", context)


def user_cart(request):
    return render(request, 'users/user_cart.html')
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:home'))

users/templates/users/login.html
{% extends 'main/base.html' %}
{% load static %}


<!-- Контент на странице -->
{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Авторизация</h2>
                <form action="{% url 'user:login' %}" method="POST">
                    {% csrf_token %}

                    <div class="mb-3">
                        <label class="form-label">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Пароль</label>
                       {{ form.password }}
                    </div>
               <button type="submit" class="btn btn-dark btn-block">Войти</button>
                </form>
                <div class="mt-3">
                    <a href="#">Забыли пароль?</a> | <a href="{% url 'user:register' %}">Создать аккаунт</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Или авторизуйтесь через:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/google.svg' %}" alt="Catalog Icon" width="16"
                             height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/facebook.svg' %}" alt="Catalog Icon" width="16"
                             height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'deps/icons/github.svg' %}" alt="Catalog Icon" width="16"
                             height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<!-- Контент на странице -->
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <img width="100" height="100"
                         src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'deps/images/baseavatar.jpg' %} {% endif %}"
                         class="img-thumbnail">
                    <form action="{% url 'user:profile' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                        {% endif %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {{ form.image }}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="form-label">Имя*</label>
                                {{ form.first_name }}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="form-label">Фамилия*</label>
                                {{ form.last_name }}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="form-label">Имя пользователя*</label>
                                {{ form.username }}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="form-label">Email*</label>
                                {{ form.email }}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
            <!-- Корзина -->
            <div class="col-md-7">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        {% include 'carts/cart.html' %}
                    </div>
                    <a class="btn btn-dark" href="../orders/create_order.html">
                        Оформить заказ
                    </a>
                </div>
            </div>
            <!-- Оформленные заказы -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Мои заказы</h3>
                    <!-- Разметка заказов -->
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading1">
                                    <button class="accordion-button" type="button"
                                            data-bs-toggle="collapse" data-bs-target="#collapse1"
                                            aria-expanded="false" aria-controls="collapse1">
                                        Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong
                                            class="mx-2"> В обработке</strong>
                                    </button>
                                </h2>
                                <div id="collapse1" class="accordion-collapse collapse show"
                                     aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                            <tr>
                                                <th>Товар</th>
                                                <th>Количество</th>
                                                <th>Цена</th>
                                                <th>Общая стоимость</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><a class="text-white" href="#">Комплект стол и три
                                                    стула</a></td>
                                                <td>1</td>
                                                <td>255.00 $</td>
                                                <td>255.00 $</td>

                                            </tr>
                                            </tbody>
                                        </table>
                                        <div class="d-flex justify-content-between">
                                            <p><strong>Итого:</strong></p>
                                            <p><strong>255.00 $</strong></p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading2">
                                    <button class="accordion-button collapsed" type="button"
                                            data-bs-toggle="collapse" data-bs-target="#collapse2"
                                            aria-expanded="false" aria-controls="collapse2">
                                        Заказ № 248 - 01 августа 2023 11:28 | Статус:
                                        <strong>Получен</strong>
                                    </button>
                                </h2>
                                <div id="collapse2" class="accordion-collapse collapse"
                                     aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                            <tr>
                                                <th>Товар</th>
                                                <th>Количество</th>
                                                <th>Цена</th>
                                                <th>Общая стоимость</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td><a class="text-white" href="#">Стул офисный</a></td>
                                                <td>2</td>
                                                <td>30.00 $</td>
                                                <td>60.00 $</td>

                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Закончилась разметка заказов -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/registration.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<!-- Контент на странице -->
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action="{% url 'user:register' %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя</label>
                            <input type="text" class="form-control" id="id_first_name"
                                   placeholder="Введите ваше имя" required name="first_name">
                            {% if form.first_name.errors %}
                            <!-- Оповещения в формах -->
                            <div class="alert alert-danger alert-dismissible fade show">Ошибка</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия</label>
                            <input type="text" class="form-control" id="id_last_name"
                                   placeholder="Введите вашу фамилию" required name="last_name">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username"
                                   placeholder="Введите ваше имя пользователя" required name="username">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email</label>
                            <input type="email" class="form-control" id="id_email"
                                   placeholder="Введите ваш email" required name="email">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль</label>
                            <input type="password" class="form-control" id="id_password1"
                                   placeholder="Введите пароль" required name="password1">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                                   placeholder="Подтвердите пароль" required name="password2">
                        </div>
                    </div>
                    <button type="submit"
                            class="btn btn-dark btn-block">Зарегистрироваться
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_cart.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include 'carts/cart.html' %}
                    <!-- Закончилась разметка корзины -->
                </div>
                <a class="btn btn-dark" href="../orders/create_order.html">
                    Оформить заказ
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}